# -*- coding: utf-8 -*-
"""score.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17IKTmjIgD8lQN8Nx61CDI3X2hZmJbq4H
"""

grades_list_str = input().split()

total_sum = 0
count = 0

for grade_str in grades_list_str:
  grade = int(grade_str)
  total_sum += grade
  count += 1

if count > 0:
  average = total_sum / count
  print(f"平均數為: {average}")
else:
  print("沒有輸入任何數字。")